# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Massimo Gallo's personal website
email:
description: >- # this means to ignore newlines until "baseurl:"
  Massimo Gallo is a Principal Engineer at Huawei Technologies Co.,Ltd in Paris since 2019. 
  He obtained the Ph.D. in Networks and computer science from Telecom ParisTech, Paris, France 
  in 2012, performing his graduate research at Orange Labs, France Telecom, Paris, France. He 
  spent six years as a researcher at BellLabs, Nokia working on Information Centric Networking 
  and High-speed packet processing. His work has been published in several top tier international 
  conferences (e.g., IEEE ICNP, Usenix ATC, ACM CoNEXT) and journals (e.g., Transaction on 
  Networking) and led to several patents. His main research interests are on the performance 
  evaluation, simulation, design and experimentation on networked systems with particular focus on 
  Programmable networks, Traffic generation, and Network Monitoring.
twitter_username: username
github_username: username
minimal_mistakes_skin: "dark"
search: true

# Build settings
markdown: kramdown
#remote_theme: "mmistakes/minimal-mistakes"
theme: minimal-mistakes-jekyll
# Outputting
# permalink: /:categories/:title/
# paginate: 5 # amount of posts to show
# paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-scholar
  - jekyll-toc


plugins_dir: ['_plugins']

author:
  name   : "Massimo Gallo"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Principal researcher at Huawei, Paris"
  email  : "first.last@huawei.com"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://gallomassimo.github.io/"
    - label: "Scholar"
      icon: "fab fa-fw fa-google"
      url: "https://scholar.google.fr/citations?user=tCb-HvoAAAAJ&hl=en"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/gallomassimo"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter"
      url: "https://twitter.com/_gallomax/"
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/massimo-gallo-782b3b38/"


footer:
  links:
    - label: "Scholar"
      icon: "fab fa-fw fa-google"
      url: "https://scholar.google.fr/citations?user=tCb-HvoAAAAJ&hl=en"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/gallomassimo"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter"
      url: "https://twitter.com/_gallomax/"
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/massimo-gallo-782b3b38/"

scholar:
  style: assets/bibliography/ieee-with-url.csl
  locale: en

  sort_by: year
  order: descending
  bibliography_list_tag: ul

  source: _bibliography
  repository: pdf
  bibliography: references
  bibliography_template: bib

  replace_strings: true

  # details_dir:    bibliography
  # details_layout: bibtex.html
  # details_link:   Details

  query: "@*"

defaults:
  # # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: false
      share: false
      related: false
  # # _pages
  # - scope:
  #     path: "_pages"
  #     type: pages
  #   values:
  #     layout: single
  #     author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
