name: Build

on:
  push:
    branches:
    - source
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v4
      with:
        ref: source
    - name: Set up Ruby 2.6 # Does not work with Ruby 3.2 (jekyll scholar uses exists)
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.6'
    - name: Build Jekyll site
      run: |
        set -xo pipefail
        rm -rf _site/*
        gem install bundler -v 2.4.22
        bundle install
        bundle exec jekyll build
    - name: Checkout master to push
      uses: actions/checkout@v4
      with:
        ref: master
        clean: false
    - name: Deploy
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      run: |
        set -xo pipefail
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        ls -Q | grep -v _site | xargs rm -rf
        mv _site/* .
        rm -rf _site
        [[ -n "$(git status --porcelain)" ]] || exit 0
        git add .
        git commit -m "Build $(git rev-parse source | grep -o '^.\{10\}')"
        git push "https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" master